### ISSUE TITLE
Add support for cflinuxfs4 stack

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/ruby-buildpack-release#3]
Hi Buildpack Developers,

can you please add support for the cflinuxfs4 stack? We have already an experimental ops file for cf-deployment to enable the new stack:
https://github.com/cloudfoundry/cf-deployment/blob/main/operations/experimental/add-cflinuxfs4.yml

There is also a job in the cf-deployment release pipeline which runs CATs with cflinuxfs4:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4

The current state of the cflinuxfs4 integration in cf-deployment is maintained in this issue:
https://github.com/cloudfoundry/cf-deployment/issues/989

Thanks and Best Regards,

  Jochen on behalf of the ARD WG.

**Comment by arjun024** [comment]
Hi,
We have work scheduled to get the buildpack support cflinuxfs4

**Comment by arjun024** [comment]
This is available with the release of https://github.com/cloudfoundry/ruby-buildpack-release/releases/tag/1.9.0
